@baseUrl = https://whispering-lowlands-47274.herokuapp.com
### Get Persons Collection
GET {{baseUrl}}/api/persons

### Get Person w/ valid id (non empty collection)
GET {{baseUrl}}/api/persons/1

### Get Person w/ invalid id
GET {{baseUrl}}/api/persons/-1

### Get Info Page
GET {{baseUrl}}/info
