### POST person with valid body (send multiple times to test name conflicts)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Spam and Eggs",
    "number": "2348000000000"
}

### POST person with malformed body
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Spam and Eggs",
    "number": spam
}

### POST person with empty body
POST http://localhost:3001/api/persons/
Content-Type: application/json

### POST person with wrong Content-Type
POST http://localhost:3001/api/persons/
Content-Type: application/not-json

{
    "name": "Spam and Eggs and Spam",
    "number": "2348000000000"
}