@baseUrl = https://whispering-lowlands-47274.herokuapp.com
@contentType = application/json;charset=utf-8

### POST person with valid body (send multiple times to test name conflicts)
POST {{baseUrl}}/api/persons/
Content-Type: {{contentType}}

{
    "name": "Spam and Eggs",
    "number": "2348000000000"
}

### POST person with malformed body
POST {{baseUrl}}/api/persons/
Content-Type: {{contentType}}

{
    "name": "Spam and Eggs",
    "number": spam
}

### POST person with empty body
POST {{baseUrl}}/api/persons/
Content-Type: {{contentType}}

### POST person with wrong Content-Type
POST {{baseUrl}}/api/persons/
Content-Type: application/not-json

{
    "name": "Spam and Eggs and Spam",
    "number": "2348000000000"
}